// buildAss is pure; render tests run real ffmpeg on tiny lavfi-generated fixtures
// (doc 13 §2: 2s media fixtures generated by script, not committed binaries).
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { join } from "node:path";
import {
  buildAss,
  cleanup,
  computeKeepSegments,
  ffmpegAvailable,
  keptDuration,
  makeTimeMapper,
  probe,
  renderClip,
  renderSlideshowVo,
  runFfmpeg,
  thumbnail,
  tmpDir,
  worthTrimming,
} from "../src";

describe("buildAss", () => {
  const segments = [
    {
      start: 0,
      end: 2.5,
      text: "hello viral engine",
      words: [
        { start: 0, end: 0.5, text: "hello" },
        { start: 0.6, end: 1.4, text: "viral" },
        { start: 1.4, end: 2.5, text: "engine" },
      ],
    },
    { start: 2.5, end: 4, text: "plain segment {no words}" },
  ];

  test("emits valid ASS structure with karaoke tags", () => {
    const ass = buildAss({ segments });
    expect(ass).toContain("[Script Info]");
    expect(ass).toContain("[V4+ Styles]");
    expect(ass).toContain("[Events]");
    expect(ass).toContain("PlayResX: 1080");
    expect(ass).toContain("Style: Default,Inter,72");
    // karaoke: 0.5s word = {\k50}
    expect(ass).toContain("{\\k50}hello");
    // silent gap 0.6→0.5 = 0.1s = {\k10}
    expect(ass).toContain("{\\k10}{\\k80}viral");
    expect(ass).toContain("Dialogue: 0,0:00:00.00,0:00:02.50,Default");
  });

  test("escapes braces in plain text and formats times", () => {
    const ass = buildAss({ segments });
    expect(ass).toContain("plain segment \\{no words\\}");
    expect(ass).toContain("0:00:02.50,0:00:04.00");
  });

  test("style overrides apply", () => {
    const ass = buildAss({
      segments: [{ start: 0, end: 1, text: "x" }],
      style: { fontName: "Bricolage Grotesque", fontSize: 64, playResX: 1920, playResY: 1080 },
    });
    expect(ass).toContain("Style: Default,Bricolage Grotesque,64");
    expect(ass).toContain("PlayResX: 1920");
  });
});

describe("silence trim (research §Part-1)", () => {
  // words with a big 2.0-2.4s silence, then a 6.0s+ silence before the last word
  const words = [
    { start: 0.2, end: 0.6 },
    { start: 0.7, end: 1.1 },
    { start: 1.2, end: 2.0 }, // ← 2.4s gap after this (silence)
    { start: 4.4, end: 4.9 },
    { start: 5.0, end: 5.4 }, // ← 3.1s gap after this (silence)
    { start: 8.5, end: 9.0 },
  ];

  test("computeKeepSegments drops long pauses, merges close words", () => {
    const keep = computeKeepSegments(words, 0, 10, { padSec: 0.05, maxGapSec: 0.4 });
    expect(keep.length).toBe(3); // three spoken islands
    // total kept ≈ (2.0-0.15)+(5.4-4.35)+(9.0-8.45) with 0.05 pad both sides
    expect(keptDuration(keep)).toBeLessThan(10);
    expect(worthTrimming(keep, 0, 10)).toBe(true); // ~5.5s of silence removed
    // first island covers the first three words as one span
    expect(keep[0]?.start).toBeCloseTo(0.15, 2);
    expect(keep[0]?.end).toBeCloseTo(2.05, 2);
  });

  test("no meaningful silence → single span, not worth trimming", () => {
    const dense = [
      { start: 0.1, end: 0.5 },
      { start: 0.6, end: 1.0 },
      { start: 1.1, end: 1.5 },
    ];
    const keep = computeKeepSegments(dense, 0, 1.6);
    expect(keep.length).toBe(1);
    expect(worthTrimming(keep, 0, 1.6)).toBe(false);
  });

  test("makeTimeMapper collapses removed gaps onto the compressed timeline", () => {
    const keep = [
      { start: 2, end: 4 },
      { start: 10, end: 12 },
    ];
    const map = makeTimeMapper(keep);
    expect(map(2)).toBeCloseTo(0, 5); // first kept sample → 0
    expect(map(3)).toBeCloseTo(1, 5); // 1s into span 1
    expect(map(4)).toBeCloseTo(2, 5); // end of span 1
    expect(map(7)).toBeCloseTo(2, 5); // inside removed gap → snaps to span-1 end
    expect(map(11)).toBeCloseTo(3, 5); // 1s into span 2 → 2 + 1
  });

  test("empty words → whole window kept, nothing trimmed", () => {
    const keep = computeKeepSegments([], 5, 20);
    expect(keep).toEqual([{ start: 5, end: 20 }]);
    expect(worthTrimming(keep, 5, 20)).toBe(false);
  });
});

// ── real-ffmpeg integration ────────────────────────────────────────
const haveFfmpeg = await ffmpegAvailable();
const t = haveFfmpeg ? test : test.skip;
if (!haveFfmpeg) console.warn("media integration: ffmpeg not found — render tests skipped");

let dir = "";
let srcVideo = "";
let srcAudio = "";
let srcImage1 = "";
let srcImage2 = "";

beforeAll(async () => {
  if (!haveFfmpeg) return;
  dir = await tmpDir("media-test");
  srcVideo = join(dir, "src.mp4");
  srcAudio = join(dir, "vo.mp3");
  srcImage1 = join(dir, "img1.png");
  srcImage2 = join(dir, "img2.png");
  // 3s 640x360 test video with tone
  await runFfmpeg([
    "-f",
    "lavfi",
    "-i",
    "testsrc2=size=640x360:rate=30:duration=3",
    "-f",
    "lavfi",
    "-i",
    "sine=frequency=440:duration=3",
    "-c:v",
    "libx264",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-shortest",
    srcVideo,
  ]);
  // 2s VO-style mp3
  await runFfmpeg(["-f", "lavfi", "-i", "sine=frequency=330:duration=2", srcAudio]);
  // two still frames
  await runFfmpeg([
    "-f",
    "lavfi",
    "-i",
    "testsrc2=size=640x360:rate=1:duration=1",
    "-frames:v",
    "1",
    srcImage1,
  ]);
  await runFfmpeg([
    "-f",
    "lavfi",
    "-i",
    "color=c=steelblue:size=640x360:rate=1:duration=1",
    "-frames:v",
    "1",
    srcImage2,
  ]);
});

afterAll(async () => {
  if (dir) await cleanup(dir);
});

describe("render pipeline (real ffmpeg)", () => {
  t("probe reads duration/size/audio", async () => {
    const p = await probe(srcVideo);
    expect(p.durationSec).toBeGreaterThan(2.5);
    expect(p.width).toBe(640);
    expect(p.height).toBe(360);
    expect(p.hasAudio).toBe(true);
  });

  t(
    "renderClip center-crop cuts a captioned vertical clip",
    async () => {
      const ass = join(dir, "clip.ass");
      await Bun.write(
        ass,
        buildAss({
          segments: [{ start: 0, end: 1.5, text: "clip caption" }],
          style: { playResX: 270, playResY: 480, fontSize: 28, marginV: 60 },
        }),
      );
      const out = join(dir, "clip.mp4");
      await renderClip({
        sourcePath: srcVideo,
        startSec: 0.5,
        endSec: 2.5,
        out,
        size: { w: 270, h: 480 },
        cropMode: "center",
        assPath: ass,
      });
      const p = await probe(out);
      expect(p.width).toBe(270);
      expect(p.height).toBe(480);
      expect(p.durationSec).toBeGreaterThan(1.5);
      expect(p.durationSec).toBeLessThan(2.6);
    },
    60_000,
  );

  t(
    "renderClip blur-pad keeps 16:9 content inside 9:16",
    async () => {
      const out = join(dir, "clip-blur.mp4");
      await renderClip({
        sourcePath: srcVideo,
        startSec: 0,
        endSec: 1.5,
        out,
        size: { w: 270, h: 480 },
        cropMode: "blur-pad",
      });
      const p = await probe(out);
      expect(p.width).toBe(270);
      expect(p.height).toBe(480);
    },
    60_000,
  );

  t(
    "renderClip with keepSegments concats spoken spans into a shorter clip",
    async () => {
      const out = join(dir, "clip-trim.mp4");
      // keep 0.0-0.8 and 2.0-2.8 of the 3s source → ~1.6s output (1.4s of middle removed)
      await renderClip({
        sourcePath: srcVideo,
        startSec: 0,
        endSec: 3,
        out,
        size: { w: 270, h: 480 },
        cropMode: "center",
        keepSegments: [
          { start: 0.0, end: 0.8 },
          { start: 2.0, end: 2.8 },
        ],
      });
      const p = await probe(out);
      expect(p.width).toBe(270);
      expect(p.height).toBe(480);
      expect(p.hasAudio).toBe(true);
      // ~1.6s of kept content, not the full 3s
      expect(p.durationSec).toBeGreaterThan(1.3);
      expect(p.durationSec).toBeLessThan(2.1);
    },
    60_000,
  );

  t(
    "renderClip speaker mode pans a 9:16 window via sendcmd crop",
    async () => {
      const out = join(dir, "clip-speaker.mp4");
      // 640×360 landscape → a 9:16 window that pans left→right→center following the track
      await renderClip({
        sourcePath: srcVideo,
        startSec: 0,
        endSec: 2,
        out,
        size: { w: 270, h: 480 },
        cropMode: "speaker",
        speakerTrack: [
          { t: 0, cx: 0.3, cy: 0.4 },
          { t: 1, cx: 0.7, cy: 0.4 },
          { t: 2, cx: 0.5, cy: 0.4 },
        ],
      });
      const p = await probe(out);
      expect(p.width).toBe(270);
      expect(p.height).toBe(480);
      expect(p.durationSec).toBeGreaterThan(1.5);
      // the sendcmd command file was written next to the output
      expect(await Bun.file(`${out}.crop.txt`).exists()).toBe(true);
    },
    60_000,
  );

  t(
    "renderSlideshowVo builds a ken-burns slideshow timed to the VO",
    async () => {
      const ass = join(dir, "slide.ass");
      await Bun.write(
        ass,
        buildAss({
          segments: [{ start: 0, end: 2, text: "slideshow caption" }],
          style: { playResX: 270, playResY: 480, fontSize: 28, marginV: 60 },
        }),
      );
      const out = join(dir, "slideshow.mp4");
      await renderSlideshowVo({
        images: [srcImage1, srcImage2],
        audioPath: srcAudio,
        assPath: ass,
        out,
        size: { w: 270, h: 480 },
        kenBurns: true,
      });
      const p = await probe(out);
      expect(p.width).toBe(270);
      expect(p.height).toBe(480);
      expect(p.hasAudio).toBe(true);
      expect(Math.abs(p.durationSec - 2)).toBeLessThan(0.8);
    },
    120_000,
  );

  t(
    "thumbnail extracts a jpg",
    async () => {
      const out = join(dir, "thumb.jpg");
      await thumbnail(srcVideo, 1, out);
      expect(await Bun.file(out).exists()).toBe(true);
      expect((await Bun.file(out).arrayBuffer()).byteLength).toBeGreaterThan(1000);
    },
    30_000,
  );
});
